### ISSUE TITLE
Better examples

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#10]
Supply example data and a vignette stepping though an example workflow of analysis.

**Comment by jcarlis3** [comment]
The sparrow example dataset is now part of the package in the form of two .rda files, `sparrow.dists`, and `sparrow.covs`.  The help doc examples for the 5 or so most-used functions now use these data.  See, for example, `F.dfunc.estim`.

**Comment by jcarlis3** [comment]
We have created an R script (saved currently in the vignette folder) called `vignette.sparrow.example` that walks through an analysis workflow.  A more formal vignette document, or a page on the package's GitHub wiki might be better options for users to find and easily step through a tutorial analysis.

**Comment by tmcd82070** [comment]
A nice vignette has been created.
