### ISSUE TITLE
Update help docs for sparrow and thrasher example data

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#101]
The help documentation I originally wrote for the sparrow and thrasher datasets that are currently built into `Rdistance` is pretty messy.  This applies to:

- `sparrowDetectionData`
- `sparrowSiteData`
- `thrasherDetectionData`
- `thrasherSiteData`

A few notes for when I get around to cleaning these up:

1)  The Description section appears twice, once up in the title block (see screenshot of pdf manual below).  Better use of the `@description` and `@details` tags would probably fix this.

2)  Parts of the help docs are redundant -- the sparrow help doc describes both the sparrow and thrasher datasets, and same for the thrasher help doc.  Given the interest in new example datasets (#99), it'd be best to document each independently.

3)  An analysis of each dataset has now been published and can be added to the `@source` or `@references` tags.

**Sage Thrasher data**
Carlisle, J. D., A. D. Chalfoun, K. T. Smith, and J. L. Beck. 2018. Nontarget effects on songbirds from habitat manipulation for Greater Sage-Grouse: Implications for the umbrella species concept. The Condor: Ornithological Applications 120:439–455. https://doi.org/10.1650/CONDOR-17-200.1

**Brewer's Sparrow data**
Carlisle, J. D., and A. D. Chalfoun. 2020. The abundance of Greater Sage-Grouse as a proxy for the abundance of sagebrush-associated songbirds in Wyoming, USA. Avian Conservation and Ecology 15(2):16. https://doi.org/10.5751/ACE-01702-150216

![image](https://user-images.githubusercontent.com/10441106/130137599-cebae43d-6074-4957-b4cb-31c922a764a7.png)

**Comment by tmcd82070** [comment]
In an effort to get re-acquainted with Rdistance, I addressed this 'easy' issue.  @jcarlis3 should check formatting and especially text of the data set documentation files. In particular the @source sections.  

I moved the general statement about the four data sets to the Rpackage general help file. 

Also, a better description of the sage thrasher data is needed.  I think we should mention the number of transects.  I think we should say something like, "#' Point transect data collected in central Wyoming from 120 points
 on __XXX__ transects (each YYY m long) surveyed for Sage Thrashers by the Wyoming Cooperative 
Fish & Wildlife Research Unit in 2013. See package vignettes for tutorials of the basic analysis. "
