### ISSUE TITLE
PDF documentation files 404 from CRAN

### ISSUE THREAD

**Issue by prairie-rex** [tmcd82070/Rdistance#105]
All the PDF links within this github lead to 404s since the package is no longer on CRAN.

**Comment by tmcd82070** [comment]
Links to CRAN are broken and will be fixed with the new Cran submission. New cran submission is in process. Meanwhile, development version on git hub is stable and documentation upon install is good. Also, wiki is updated.

**Comment by jcarlis3** [comment]
Verified that vignette PDF links on CRAN are now good (as of Rdistance version 3.0.0).  And the vignette links in the README on the [Rdistance GitHub page](https://github.com/tmcd82070/Rdistance) are also good.  The tutorials listed on the [Rdistance Wiki](https://github.com/tmcd82070/Rdistance/wiki) are currently out of date.

**Comment by tmcd82070** [comment]
Resolved when Rdistance 3.0.0 was accepted by CRAN
