### ISSUE TITLE
predict.dfunc returns probabilities >1

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#107]
Something seems awry in `predict.dfunc` when factor covariates are present.  Predicted values of probability of detection are > 1 for some combos of distance and factor level.
```
# Load example sparrow data (line transect survey type)
data(sparrowDetectionData)
data(sparrowSiteData)


# Fit a second half-normal detection function, now including
# a categorical covariate for observer who surveyed the site (factor, 5 levels)
dfuncObs <- dfuncEstim(
  formula = dist ~ observer,
  detectionData = sparrowDetectionData,
  siteData = sparrowSiteData,
  likelihood = "halfnorm",
  w.hi = units::as_units(100, "m")
)

# Print results
# And plot the detection function for each observer
dfuncObs

newdata <- data.frame(observer = levels(sparrowSiteData$observer))
plot(dfuncObs, newdata = newdata)
```
![image](https://user-images.githubusercontent.com/10441106/231954419-21cd999d-471a-4201-94c0-bb7e5debd9f5.png)

```
# Show predictions > 1
predict(dfuncObs, newdata = newdata, type = "")
```

![image](https://user-images.githubusercontent.com/10441106/231954605-b9a2da96-3c0c-4565-8935-8cbbb2cb644a.png)

**Comment by tmcd82070** [comment]
I had a transpose in the wrong place.  Inside, unscaled predictions in matrix y were transposed from what they should have been, and the scaling did not work right.  Hence the whacky results.  Without covariates, there was ever only one distance function so transposition did not make a difference and results were okay.  I eliminated the transpose, and everything works.  No idea where the unintentional transpose came from.

This was fixed as of commit 21af72c20b8a20eb27a682d6a3c4c960ebc87626
