### ISSUE TITLE
Point count option

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#19]
Current version (1.2.2) only handles line transect survey designs.  Need to add functionality for point count survey designs.

**Comment by tmcd82070** [comment]
@AidanMcDonald has completed low-level routines and they are working.  Higher level routines need to be checked and tested.

**Comment by tmcd82070** [comment]
Initial version of point transects, in low level routines at least, is implemented and tested. Additional testing between now and workshop will be done.
