### ISSUE TITLE
Bootstrap detections

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#20]
The bootstrap method used to compute CIs for abundance (in F.abund.estim and F.automated.CDA) currently resamples transects.  Add option of resampling detections.

**Comment by tmcd82070** [comment]
WE need to think about this.  I am not sure this option is a good thing to
do in many cases. If someone wants to bootstrap individual sightings, they
could program it themselves with calls to F.abund.estim( bs=FALSE ) in a
loop.

**Comment by jcarlis3** [comment]
Prior to version 1.3.1, the `F.abund.estim` and `F.automated.CDA` functions included a `bs.method` argument with the only option being "transects" (resample transects to generate bias-corrected CIs for abundance).  This argument has been removed (as of version 1.3.1), as we do not currently plan to offer any other resampling options.  See the previous comment for those interested in the option to resample detections.
