### ISSUE TITLE
Adding covariates to the detection function

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#23]
We are working to build-in the option of modeling the detection function as a function of covariates (e.g., habitat, observer ,etc.).  Currently (v 1.3.2), this isn't possible in Rdistance.

**Comment by tmcd82070** [comment]
As of today, this issue is nearly finished.  @AidanMcDonald will perform final checks of gamma function. 

Automated fitting routine may need inspection/testing

**Comment by tmcd82070** [comment]
Covariates are tested and implemented to the point that we can close this and open bug report for specific problems.
