### ISSUE TITLE
Migrate .Rd documentation to roxygen format

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#24]
I wrote the original documentation before I discovered roxygen.  We need to migrate all the documentation in the `man/*.Rd` files to roxygen format.  Roxygen format puts the documentation at the front of the code files using `#'` as a comment character and includes terms like `@export`, `@descrption`, etc.

**Comment by jcarlis3** [comment]
@AidanMcDonald 
For examples, see my [umbrella](https://github.com/jcarlis3/umbrella) package.  The `roxygen2` syntax goes at the head of the .R scripts, then creates the .Rd files in man after running `devtools::document`.  I found it handy to document the items with no .R file (the main package help, and dataset helps) in a phony help.R file.  Also, I've updated the dataset help files (as .Rd) in the `ExampleData` branch, so let's sync that to master first.

**Comment by jcarlis3** [comment]
The `ExampleData` branch has been merged back into `master`.

**Comment by tmcd82070** [comment]
Except for documentation of all the 4 data sets, this is done. All documentation of functions is in Roxygen format.

**Comment by jcarlis3** [comment]
Converted the helps for the package and the 4 example datasets to roxygen format:  https://github.com/tmcd82070/Rdistance/commit/af376c3f428a8fc2d159c9c0936df7ad83619161

For the record, the `Rd2roxygen` package makes this a breeze:
https://yihui.name/rd2roxygen/
