### ISSUE TITLE
Automated estimation routines need checked

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#27]
After feature enhancements made by @AidanMcDonald summer 2017, this routine will almost certainly not work.  This routine should be updated to work with point transects and covariates (and SE estimates - bootstrapping).

**Comment by jcarlis3** [comment]
This routine (now called `autoDistSamp`) now works for point and line transect data, as long as there are no covariates.  Including covariates will likely require some updates in `autoDistSamp`.

**Comment by jcarlis3** [comment]
This routine now runs with points or lines, with covariates or without.  Still needs some testing.

**Comment by jcarlis3** [comment]
Testing has all checked out.  Closing.
