### ISSUE TITLE
Re-evaluate input data frames

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#30]
Presently, we accept 2 data frames, one containing detections and one containing transects, as input to F.dfunc.estim and F.abund.estim.  When covariates are included, we currently require one data frame with the covariates and detections merged. 

Consider changing to allow two types: 

* Two data frames.  One for detections, one for transects/points. 
* One data frame. This would contain detections, covariates and NA for transects/points where nothing was seen

**Comment by jcarlis3** [comment]
We retained the requirement that two data.frames (one for detections and one for sites) are required for input into the three primary functions:  `F.dfunc.estim`, `F.abund.estim`, and `F.automated.CDA`.
@tmcd82070 , If the user does not have covariates in their detection function, do they still have to provide the `site.data` to `F.dfunc.estim`?

**Comment by tmcd82070** [comment]
If no covariates are included, only `detection.data` need be specified.  Here is the logic at the beginning of `F.dfunc.estim`. 

```R 
if(!missing(detection.data) & !missing(site.data)){
    if( is.null(transectID) ){
      transectID <- intersect( names(detection.data), names(site.data) )
      if( point.transects ){
        pointID <- NULL  # multiple pts per transect not allowed when no transectID specified
      } 
    }
    if( point.transects ){
      siteID.cols <- c(transectID, pointID)
    } else {
      siteID.cols <- c(transectID)
    }
    data <- merge(detection.data, site.data, by=siteID.cols)
  } else if(!missing(detection.data)){
    data <- detection.data
  } else{
    data <- NULL
  }
```

I have update the help for `F.dfunc.estim` to explain these requirements.  Here is the updated help: 

**Data frame requirements**

The following explains conditions under which various combinations of the input data frames are required.

1. Detection data and site data both required:
Both detection.data and site.data are required if site level covariates are specified on the right-hand side of formula. Detection level covariates are not currently allowed.

2. Detection data only required:
The detection.data data frame alone can be specified if no covariates are included in the distance function (i.e., right-hand side of formula is "~1"). Note that this routine (F.dfunc.estim) does not need to know about sites where zero targets were detected, hence site.data can be missing when no covariates are involved.

3. Neither detection data nor site data required
Neither detection.data nor site.data are required if all variables specified in formula are within the scope of this routine (e.g., in the global working environment). Scoping rules here work the same as for other modeling routines in R such as lm and glm. Like other modeling routines, it is possible to mix and match the location of variables in the model. Some variables can be in the .GlobalEnv while others are in either detection.data or site.data.

**Comment by tmcd82070** [comment]
I have decided not to implement the one data frame option.  I.e., from the original issue, I have decided to require two data frames for now (i.e., no NA's for distances), with the above caveats in F.dfunc.estim. 

Hence, we can close this issue.
