### ISSUE TITLE
Vignette and example updates

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#31]
With new features programmed during summer 2017, the vignettes and some examples are out of date.  Update the vignettes etc to include point transects and covariate examples.

**Comment by jcarlis3** [comment]
We'll need to update the material on the Wiki as well.  Did @AidanMcDonald update the help docs concurrent with changes to code?

**Comment by tmcd82070** [comment]
@AidanMcDonald has been, or will complete, the technical documentation of
all functions in the package before he leaves.

After he leaves, we will need to review the documentation for accuracy and
compatibility across functions.  Then, you are right, we'll need to update
the Wiki (and vignettes both).

*-------------------------------------------------------*
*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
Publications: Google Scholar
<https://scholar.google.com/citations?user=K1031qoAAAAJ&hl=en>, ResearchGate
<https://www.researchgate.net/profile/Trent_Mcdonald>
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by jcarlis3** [comment]
I've removed the vignettes, as they are now all out of date.  Once version 2.x is stable, I will update and add vignettes.  Some of the workshop material may make for useful vignettes.

I hope to update all the examples embedded in the code this week.

**Comment by jcarlis3** [comment]
The examples within the help docs are now updated (as of version 2.0.5).  Updating and including vignettes remains unaddressed.

**Comment by tmcd82070** [comment]
Vignettes go a major overhaul in version 2.1.1.
