### ISSUE TITLE
Covariates in Gamma function

### ISSUE THREAD

**Issue by AidanMcDonald** [tmcd82070/Rdistance#32]
Gamma function isn't working when covariates are included.

**Comment by jcarlis3** [comment]
You can fit a Gamma function with covariates using the sparrow data.  But it issues a bunch of warnings, and the plot makes clear there are issues.  Nonetheless, we should fix or prohibit this use case.

`sparrow.dfunc <- dfuncEstim(formula=dist~shrub, detectionData=sparrowDetectionData, siteData=sparrowSiteData,
                            likelihood="Gamma", w.hi=100)`

![image](https://user-images.githubusercontent.com/10441106/30666716-78df72dc-9e12-11e7-82ec-a102e1eb3645.png)

![image](https://user-images.githubusercontent.com/10441106/30666744-8fd59656-9e12-11e7-8b63-64b3ff244f83.png)

**Comment by jcarlis3** [comment]
I've added an error message in `dfuncEstim` for the time being, assuming we add this functionality later.  If there are covariates and the likelihood is Gamma, the routine will error out.

![image](https://user-images.githubusercontent.com/10441106/30720549-34e54646-9ee5-11e7-8c96-b6dadd953c8e.png)

**Comment by tmcd82070** [comment]
Covariates are allowed in Gamma distance function as of version 2.2.0
