### ISSUE TITLE
Abundance estimates with point transects

### ISSUE THREAD

**Issue by AidanMcDonald** [tmcd82070/Rdistance#33]
Abundance estimates from point transect data do not match results from other packages.

**Comment by jcarlis3** [comment]
This is close to resolved.  @tmcd82070 , building the `newdata` argument into `EDR` is the next step.

**Comment by tmcd82070** [comment]
`newdata` parameter implemented in `EDR` function.  As far as I can tell, `EDR` now correctly computes effective radius with and without covariates.

I was unable to check results against `Distance`.  This check should be done.   I ran `abundEstim`   and everything looked reasonable. 

I'm closing this under the assumption that the check with `Distance` shows same results.
