### ISSUE TITLE
Errors in dfunc plotting for point transects

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#36]
See `test_points_noCovars.R` to reproduce.

1)
`plot(dfunc)` - the y axis isn't probability of detection for point transects (note how the y-intercept is 0).  Would have to rescale bars and detection function (red line).  I think this version with no rescaling is fine, but need to relabel y.

![image](https://user-images.githubusercontent.com/10441106/29990421-91447de8-8f37-11e7-9153-cb2cf7916316.png)

2)
When `plot.bs=TRUE` in `F.abund.estim`, the bootstrap resamples of the detection function appear to be plotting as if y was detection probability (and the red line of the fitted detection function).  But it plots on top of the old plot where y isn't detection probability.

![image](https://user-images.githubusercontent.com/10441106/29990442-d0395de8-8f37-11e7-8d76-2e2d31a89270.png)

**Comment by tmcd82070** [comment]
## Re Y axis label
Right. Y axis should be something like "x*g(x)" or "Observation density" or "Observation curve".  The red line is f(x) * x, where f(x) is the detection density. 

## Re Bootstrap plotting
I think Aidan is plotting g(x) each bootstrap, but underneath the bins show g(x)*x.  So, probably best thing is to just erase (not plot) the bars and first red line.

**Comment by jcarlis3** [comment]
One more issue with bootstrap plotting in `F.abund.estim`.
See `test_lines_covars.R` to reproduce.

When line data with a covariate, the bootstrap replicates of the detection function (blue lines, hard to see) and the re-plotting of the original detection function (red line plotted over blue lines) are in the wrong place.  The bootstrap-generated CIs appear accurate, so I think this issue is in plotting only, not the bootstrap itself.

![image](https://user-images.githubusercontent.com/10441106/30130981-522e2de6-9308-11e7-87d9-03282636c3ae.png)

**Comment by jcarlis3** [comment]
And this new issue shown for line data with covariates also applies to point data with covariates.
See `test_points_covars.R` to reproduce.

![image](https://user-images.githubusercontent.com/10441106/30131687-eba81ca0-930a-11e7-8d3f-679be82f7b52.png)

**Comment by jcarlis3** [comment]
The scaling issues above have been resolved.  Two minor issues remain:

1.  The y-axis label is incorrect.  This is f(x), not g(x), yes?  So "observation density"?  Should there be an option to plot detection probability?  Or at least a demo on how to plot detection probability for point data in a vignette or something?
2.  The bins no longer appear.

![image](https://user-images.githubusercontent.com/10441106/31255127-842c5952-a9e8-11e7-9053-0be2584da3eb.png)

**Comment by tmcd82070** [comment]
# Y-axis label fixed
# space added above and clipping stopped. 
![image](https://user-images.githubusercontent.com/4823244/31972189-a7ce94ee-b8dc-11e7-8c1f-f87529248489.png)
