### ISSUE TITLE
Updates in F.dfunc.estim

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#37]
@tmcd82070 

I see these as the primary fixes needed in `F.dfunc.estim`.  If you can tackle these, I'll work on `F.abund` and `F.auto`.

1. See other [issue on input datasets](https://github.com/tmcd82070/Rdistance/issues/30).  For now, since we're restricting to site-level covariates on detection, it makes sense to me to have `detection.data` and `site.data` as two input datasets (same inputs for `F.dfunc`, `F.abund`, and `F.auto`).  `site.data` could be NULL in `F.dfunc` if the user wants to fit a `dist~1` model.  Merge `detection.data` and `site.data` first, then proceed?  Messes with the `match.call` section, which I don't understand well.  Currently, `F.dfunc` accepts `data`, which the user has to merge ahead of time.
2. As you suggested, limit expansions to 0 when covars are present.
3. Do we report SE or CIs for the effect of the covar on the detection function?  Should we?

**Comment by tmcd82070** [comment]
@jcarlis3 

1. I was not able to allow `F.dfunc.estim` to take both detections and site data frames AND merge them 
in the routine if covariates are present.  There is some subtlety in the eval() method for a model.frame object that I do not understand.  In lieu of that, I changed the name of the data frame argument to 'detection.data'.  This does not solve the problem, but it might make more sense.  Users still need to merge detections and transects before calling this routine.   I updated the documentation to reflect this change. 

2. I disallowed expansions > 0 when covariates are present.  I print a warning if this (for now) illegal condition is requested. 

3. We should probably report SE's for coefficients on covariates.  I'll close this issue and restart another one with that topic.  For now, its low priority.

**Comment by jcarlis3** [comment]
@tmcd82070 

Thanks.  Re: 1, We'll have to figure out what the requirement that users merge detection and site data before input to `F.dfunc.estim` has on the downstream functions (`F.abund.estim` and `F.automated.CDA`), which both require detection and site data input separately.  The simple solution might be for these functions to still require detection and site data--the only catch being that if you want covariates in the detection function, your detection data must include them ahead of time (i.e., the detection data you input must be a merged version of your detection and site data).

**Comment by tmcd82070** [comment]
Yes, exactly. Any detection function covars must be in the detection.data
dataframe. A waste of space, but this should work.

I will get the merge and eval issue working at some point. It has ticked me
off.

Later, we might consider allowing only one data frame.  Zero tranects are
NA and length is included as a column.
