### ISSUE TITLE
Improve optimization

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#43]
`optim` doesn't seem to be performing particularly well.  Explore other optimization options.

**Comment by jcarlis3** [comment]
Trent and Jaime are looking into incorporating the optimization routine that appears in the `mra` package.

**Comment by tmcd82070** [comment]
We went back to `nlminb` as the default optimizer with the ability to switch back and forth using `RdistanceControl`.  This is in version 2.1.1
