### ISSUE TITLE
Specify which information criterion was calculated

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#46]
The default is to calculate and report AICc for a detection function, but the printed results were labelled "AIC".

As detailed in `AIC.dfunc`, the user could easily specify that AICc, AIC, or BIC be provided.  Should we update `AIC.dfuc` and `dfuncEstim` such that the user specifies an argument `criterion` as either "AICc", "AIC", or "BIC", and we set the current `k` and `n` arguments accordingly (and internally with no user input)?  And then when printing the `dfunc` determine which `criterion` was used and label the printout accordingly?

**Comment by tmcd82070** [comment]
Following files were modified to allow users to specify criterion for either printing or sorting: 
R/AIC.dfunc.R
R/autoDistSamp.R
R/print.abund.r
R/print.dfunc.r

Criterions allowed are "AIC", "AICc", and "BIC". 

Documentation changed accordingly.
