### ISSUE TITLE
Two-level siteIDs

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#53]
@tmcd82070  suggested implementing two-level site identifiers.  For example, if several point surveys are done along one line or grid, or to accomodate multiple visits to the same site, etc.

The help for `dfuncEstim` already discusses such compound identifiers, but I don't think it was fully implemented.

We'd need to consider what should be resampled in the bootstrap to generate CIs on abundance (`abundEstim`).

**Comment by tmcd82070** [comment]
Done in version 2.1.1
