### ISSUE TITLE
User-supplied names for required columns

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#54]
Currently, `duncEstim` and `abundEstim` require a rigid column-naming convention (e.g., "siteID", "groupsize", etc., see help docs for these functions for full list).  It would be nice to allow the user to specify the column name associated with each required column of data.  I think Trent partially implemented this for the "siteID" column in `dfuncEstim`.

**Comment by tmcd82070** [comment]
Trent wonders whether this is completely implemented.  He thinks this was done in `dfuncEstim` but maybe not in `abundEstim`.

**Comment by tmcd82070** [comment]
Implemented in version 3.0.0.
