### ISSUE TITLE
Plot not working in dfuncEstim without specifying levels of observer

### ISSUE THREAD

**Issue by mkleinsa** [tmcd82070/Rdistance#58]
When levels of observer are not sent to plot as an argument, plot function breaks:

```{r}
d2 <- dfuncEstim(dist ~ observer, detectionData=sparrowDetectionData, 
                 siteData=sparrowSiteData, likelihood="halfnorm", pointSurvey = FALSE)
plot(d2) # Can't plot without newdata specifying levels of categorical predictor
```

Traceback:

Error in eval(predvars, data, env) : object 'observer' not found 
7.eval(predvars, data, env) 
6.eval(predvars, data, env) 
5.model.frame.default(Terms, newdata) 
4.model.frame(Terms, newdata) at predict.dfunc.R#61
3.predict.dfunc(x, newdata, type = "parameters") at plot.dfunc.r#132
2.plot.dfunc(d2) 
1.plot(d2) 

If levels are sent through plot, the plot works fine:

```{r}
d2 <- dfuncEstim(dist ~ observer, detectionData=sparrowDetectionData, 
                 siteData=sparrowSiteData, likelihood="halfnorm", pointSurvey = FALSE)
plot(d2, newdata=data.frame(observer = levels(sparrowSiteData$observer)))
```

**Comment by jcarlis3** [comment]
If the dfunc has a continuous covariate and the user does not supply `newdata` in the plot call, we plot the detection function for the mean value of the covariate.
If I understand, if the dfunc has a categorical covariate and the user does not supply `newdata` in the plot call, an error is produced.
Do we just insert an informative error message to remind the user to supply `newdata`?
Or make the default to plot the first level?
Or make the default to plot levels(siteData$catCovar) as in @mkleinsa 's example?

**Comment by mkleinsa** [comment]
Do we just insert an informative error message to remind the user to supply newdata? 
If we go this route, will most users be familiar enough to know what newdata needs to be? That seems like the easiest fix.

Or make the default to plot levels(siteData$catCovar) as in @mkleinsa 's example? 
This is what I was thinking. I'd have to grab levels somehow; I'm not sure if we have that information accessible inside `plot.dfunc`. What if we could store levels in `dfunc$levels` and pull them out for use in  `plot.dfunc`?

**Comment by mkleinsa** [comment]
I'm modifying the code to throw an error message to remind the user to supply `newdata`. Do we want to throw the error message whenever the user forgets to specify `newdata`, or only when the covariate is categorical? This is an issue because the code was written to handle continuous covariates is a specific way (use the mean). If we do need to handle the error differently for categorical covariates than for continuous, how could we determine when a covariate is categorical?

**Comment by jcarlis3** [comment]
I suggest building in an informative error message with `stop()` for cases where the `dfunc` object has a categorical covariate and the user does not supply `newdata` in the `plot` call.  And leaving the continuous covariate case as-is (defaults to plot at mean value).  @tmcd82070 could help you figure out how to determine if the covariate is continuous or categorical.

**Comment by mkleinsa** [comment]
I altered `plot.dfunc` to draw the mean level of any number of ratio level covariates and the mode of any number of categorical level covariates by default. If the user wants more control over what specifically gets plotted, they simply specify it using `newdata`.
