### ISSUE TITLE
Bootstrapping in estimAbund() when siteData only has a single column fails because R automatically drops dimensions

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#66]
If the siteData is a data frame with a single column (e.g. just the siteID), then the bootstrapping fails in the abundEstim() function:

> head(site.df)
          siteID
1       MRCC-Ex1
2   SW-CT26 (65)
3      CT29 (29)
4        JBA-Ex1
5    HB-F-TO-Ex2
6 Ri-D-TS1 (205)
> abund.est       <- abundEstim(detect.func,
+                          detectionData=detect.df,
+                          siteData=site.df,
+                          area=1, R=20,
+                          bySite=FALSE)
Computing bootstrap confidence interval on N...
Error: $ operator is invalid for atomic vectors

The problem is that the sampling for the bootstrapping selects the rows of the dataframe and then drops a dimension to form a vector (default behaviour for R). 

Solution is to add a dummy column to the data frame, or to modify the bootstrapping selection to avoid dropping a dimension:

i.e. change the following lines in the estimAbund() function from
          for (i in 1:R) {
                new.siteData <- siteData[sample(nrow(siteData), 
                  nrow(siteData), replace = TRUE), ]

to

           for (i in 1:R) {
                new.siteData <- siteData[sample(nrow(siteData), 
                  nrow(siteData), replace = TRUE),, drop=FALSE ] # don't drop dimensions when selecting

Carl Schwarz
cschwarz.stat.sfu.ca@gmail.com

**Comment by tmcd82070** [comment]
Huge thanks to @cschwarz-stat-sfu-ca for this bug catch.  We did not specifically test this case. 

This error only effected point transects.  Line transects require at least `siteID` and `length` column in `siteData`. 

Fixed as suggested.  Relevant snipet is now:

```
      for (i in 1:R) {
        # sample rows, with replacement, from transect data
        new.siteData <- siteData[sample(nrow(siteData), nrow(siteData), replace=TRUE),,drop=FALSE]
``` 

Fixed in version `2.1.3`
