### ISSUE TITLE
autoDistSamp() fails with bySite=TRUE

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#67]
The autoDistSamp() fails with bySite=TRUE .....

> detect.func2 <- autoDistSamp(formula = dist ~ 1,
+                          detectionData = detect.df,
+                          siteData = site.df,
+                          pointSurvey = TRUE,
+                          plot = FALSE,
+                          area = 10000,
+                          bySite=TRUE,
+                          R =100)
Likelihood	Series	Expans	Converged?	Scale?	AICc
halfnorm	cosine	0	Yes		Ok	1537.4427
.......
Gamma			0	Yes		Ok	1529.2163
Note: Some models did not converge or had parameters at their boundaries.
Error in `$<-.data.frame`(`*tmp*`, "fitTable", value = list(like = c(3L,  : 
  replacement has 41 rows, data has 105

Problem is near the end of the function at the lines ...

    abund <- abundEstim(dfunc, detectionData = detectionData, 
        siteData = siteData, area = area, ci = ci, R = R, plot.bs = plot.bs, 
        bySite = bySite, showProgress = showProgress)
    abund$fitTable <- fit.table

When bySite=TRUE, the "abund" object is an object with the predicted density/abundance for EACH site and so you cannot add an object fitTable to it in the next line.

So either disable it, e.g.
    if(!bySite) abund$fitTable <- fit.table

or make the returned object a list with a single entry being the the dataframe
   abund <- list(abund=abundEstim ......)

Carl Schwarz

**Comment by tmcd82070** [comment]
A good catch by @cschwarz-stat-sfu-ca , and a product of not testing enough cases. 

Fixed as suggested. Fit table is only returned when bySite=F.  When bySite=T, code now stores likelihood, series, and expansions of best fitting model as attributes to the returned data frame in case user wants to reconstruct the best fitting distance function.  Relevant snipet:

```
  if( !bySite ){
    # Store the fitting table, just in case user wants it.
    abund$fitTable <- fit.table
  } else {
    attr(abund,"like.form") <- dfunc$like.form
    attr(abund,"series") <- dfunc$series
    attr(abund,"expansions") <- dfunc$expansions
  }
```

Fixed in version `2.1.3`
