### ISSUE TITLE
Vignette on relating abundance to covariates is missing

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#68]
The vignette on relating abundance to covariates is missing as referenced on the wiki page
    https://github.com/tmcd82070/Rdistance/wiki/Modeling-Abundance-in-Relation-to-Covariates

Carl Schwarz
cschwarz.stat.sfu.ca@gmail.com

**Comment by tmcd82070** [comment]
This vignette required updating when we made major updates between versions 1.3.1 and 2.1.1.  And, we never got around to it.  In addition, the old PDF was short and did not go very far (i.e., it could have been more helpful). 

The R script attached here does the trick.  It is not as well formatted as a vignette, but it demonstrates everything needed in the two-step analysis.  We will go with this script until we get a chance to clean it up visually. 

To use this script, download and change its extension to `.R`


[Example_3_TwoStage.R.txt](https://github.com/tmcd82070/Rdistance/files/2367771/Example_3_TwoStage.R.txt)
