### ISSUE TITLE
Strange plot - histogram below zero?

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [tmcd82070/Rdistance#69]
I'm fitting point-transects for many species and one of the species results has a strange plot where the histogram is below 0? Sample code and output is available at:
  
https://www.dropbox.com/sh/9kwltgm1m1b19o6/AAALk3D5aSIamSPzZaxJU-b-a?dl=0

and in the following files (need to remove the .txt from the R file)
[odd-detect-df.xlsx](https://github.com/tmcd82070/Rdistance/files/2389653/odd-detect-df.xlsx)
[inverted-plot.R.txt](https://github.com/tmcd82070/Rdistance/files/2389655/inverted-plot.R.txt)

Thanks

Carl Schwarz
cschwarz.stat.sfu.ca@gmail.com

**Comment by tmcd82070** [comment]
Oh my.  I am booked up for a day or so, but will take a look asap.  I **think** this is an issue with plotting only, not actual estimates.   

Something is obviously wrong with the scaling.  Either the scaling constant, g(x), or x.  

![image](https://user-images.githubusercontent.com/4823244/45645057-96972900-ba7c-11e8-9155-b23b37199795.png)

**Comment by tmcd82070** [comment]
Issue was distance function values < 0 at zero.  Parameters were at (beyond) boundary of parameter space.  This possibility was being trapped in line transect cases, but not for point transects. 

**Fix**: Plot is no longer inverted, a warning is issued when this occurs, and a message across the plot is printed when this occurs.  Message is "Probabilities < 0". 

**Another fix**: During testing found and fixed issue related to wonky plots when left truncation is not zero.
