### ISSUE TITLE
Estimating probability of detection at a given distance

### ISSUE THREAD

**Issue by jcarlis3** [tmcd82070/Rdistance#91]
For Horvitz-Thompson-like applications of distance sampling, the user might need to estimate the probability of detection (p) for each each group/individual detected (i.e., each row in the detection dataset).  If there are no covariates in the detection function, that p is a function of distance only.  Currently, the user needs to call the `xxx.like` function corresponding to the likelihood used in the detection function (e.g., `halfnorm.like`) to estimate p at a given distance.  Here's how that's done using the example sparrow dataset in the package and a half-normal detection function.

```
require(Rdistance)

# Load example sparrow data (line transect survey type)
data(sparrowDetectionData)

# Fit half-normal detection function
dfunc <- dfuncEstim(formula=dist~1,
                    detectionData=sparrowDetectionData,
                    likelihood="halfnorm", w.hi=100)

# Print results and plot
dfunc
plot(dfunc)

# What is the estimated detection probability
# at distances 0, 50, and 100
# See ?halfnorm.like for details
halfnorm.like(a=dfunc$fit$par, dist=c(0, 50, 100), scale=FALSE)
```

@tmcd82070 , do we consider a wrapper function that would take in the `dfunc` object and distance, and apply the appropriate `xxx.like` function?

**Comment by tmcd82070** [comment]
A `predict` method is implemented in version 0.2.2. The new predict takes a `type = "dfunc"` argument that produces what this comment suggests.  To get the same answer as this comment: 
```
predict(dfunc, type="dfunc", distances = c(0, 50, 100))
```
If covariates are present, add a `newdata` data frame to predict.  For example: 
```
predict(dfunc, type="dfunc", distances = c(0,50,100), newdata = data.frame(slope = c(20,50)))
```
will produce a 2 X 3 matrix where each row is a distance function for a separate set of covariates (here, 20 and 50) and each column is a predicted distance function height (here, at the three distances 0, 50, and 100).
