### ISSUE TITLE
EDR with confidence intervals

### ISSUE THREAD

**Issue by zielinskipp** [tmcd82070/Rdistance#92]
Hi, 

is it possible to enhance the EDR function to caluclate the CI for that statistic?

**Comment by tmcd82070** [comment]
Also the ESW function. 

May be best to return a bootstrap vector of ESW/EDR from `abundEstim`.  

Need to consider covariate values. Users want to compare ESW for covariates = x versus ESW for covariates = y.  In this case, may be best to implement in ESW/EDR function than `abundEstim`.

**Comment by tmcd82070** [comment]
As of version 2.2.0 (only on gitlab as of Jan 2023), a confidence interval for EDR or ESW is automatically calculated when a person calls `abundEstim`.  I.e., when one does the bootstrapping, confidence intervals on N and (ESW/EDR) are produced.  Simply print the abundance object to see confidence intervals.  Here is an example output: 
```
Call: dfuncEstim(formula = dist ~ 1, detectionData = sparrowDetectionData, likelihood =
   "halfnorm", pointSurvey = FALSE, w.lo = units::set_units(50, "m"), w.hi =
   units::set_units(200, "m"))
Coefficients:
       Estimate  SE        z         p(>|z|)     
Sigma  53.96697  3.252069  16.59466  7.617552e-62

Convergence: Success
Function: HALFNORM  
Strip: 50 [m] to 200 [m] 
Effective strip width (ESW): 67.26925 [m] 
                     95% CI: 63.08224 [m] to 70.67049 [m]
Probability of detection: 0.4484617 
Scaling: g(50 [m]) = 1
Log likelihood: 465.5649 
AICc: 933.1679

Density in sampled area: 2.209198e-05 [1/m^2]
                 95% CI: 1.770216e-05 [1/m^2] to 2.464364e-05 [1/m^2]

Abundance in 10000 [m^2] study area: 0.2209198
                             95% CI: 0.1770216 to 0.2464364
```
