### ISSUE TITLE
Implement multiplier for 1-sided transects

### ISSUE THREAD

**Issue by tmcd82070** [tmcd82070/Rdistance#97]
Implement the ability to analyze transects that are only one-sided.  When transects are only one-sided, the 1/2 multiplier in the density formula is something like 1/m where m = the number of sides surveyed.  Program Distance implements a user-specified multiplier for the proportion of the 2XL typical survey area that was surveyed. 

Not sure this applies to point-counts.

**Comment by jcarlis3** [comment]
Correct me if I'm wrong, but the simple workaround in the meantime to accommodate one-sided transects would simply be to divide the line lengths in half.

**Comment by tmcd82070** [comment]
Added `singleSided=` parameter to `abundEstim` in version 3.0.0.
